require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 80

Metrics/BlockLength:
  IgnoredMethods:
    - describe
    - context
    - shared_examples
    - it

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Max: 40
