version: 2.1

orbs:
  slack: circleci/slack@4.8.3

defaults: &defaults
  docker:
    - image: ruby:2.7.5

slack_context: &slack_context
  context:
    - slack

only_main: &only_main
  filters:
    branches:
      only:
        - main

only_dependabot: &only_dependabot
  filters:
    branches:
      only:
        - /^dependabot.*/

only_main_and_dependabot: &only_main_and_dependabot
  filters:
    branches:
      only:
        - main
        - /^dependabot.*/

commands:
  notify:
    steps:
      - slack/notify:
          event: fail
          channel: dev
          template: SLACK_FAILURE_NOTIFICATION
      - slack/notify:
          event: pass
          channel: builds
          template: SLACK_SUCCESS_NOTIFICATION
  configure_tools:
    steps:
      - run: ./scripts/ci/common/install-git-crypt.sh
      - run: ./scripts/ci/common/install-gpg-key.sh
      - run: ./scripts/ci/common/install-orb-deps.sh
      - run: ./scripts/ci/common/configure-git.sh
      - run: ./scripts/ci/common/configure-rubygems.sh

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - configure_tools
      - run: ./scripts/ci/steps/build.sh
      - notify

  test:
    <<: *defaults
    steps:
      - checkout
      - configure_tools
      - run: ./scripts/ci/steps/test.sh
      - notify

  prerelease:
    <<: *defaults
    steps:
      - checkout
      - configure_tools
      - run: ./scripts/ci/steps/prerelease.sh
      - notify

  release:
    <<: *defaults
    steps:
      - checkout
      - configure_tools
      - run: ./scripts/ci/steps/release.sh
      - notify

  merge_pull_request:
    <<: *defaults
    steps:
      - checkout
      - configure_tools
      - run: ./scripts/ci/steps/merge-pull-request.sh
      - notify

workflows:
  version: 2
  pipeline:
    jobs:
      - build:
          <<: *only_main_and_dependabot
          <<: *slack_context
      - test:
          <<: *only_main_and_dependabot
          <<: *slack_context
          requires:
            - build
      - merge_pull_request:
          <<: *only_dependabot
          <<: *slack_context
          requires:
            - test
      - prerelease:
          <<: *only_main
          <<: *slack_context
          requires:
            - test
      - slack/on-hold:
          <<: *only_main
          <<: *slack_context
          requires:
            - prerelease
          channel: release
          template: SLACK_ON_HOLD_NOTIFICATION
      - hold:
          <<: *only_main
          type: approval
          requires:
            - prerelease
            - slack/on-hold
      - release:
          <<: *only_main
          <<: *slack_context
          requires:
            - hold
